# Paso 5: Creación de tablas

## Librerias

In [1]:
# Generales
import pandas as pd
import numpy as np
import os 

# Ocultar warnings
import warnings
warnings.filterwarnings('ignore')

# Aumentar número de columnas que se pueden ver
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.10f}'.format
# Cada columna será tan grande como sea necesario para mostrar todo su contenido
pd.set_option('display.max_colwidth', 0)

In [2]:
# Cambiar directorio para importar modulos y datos fácilmente
os.chdir('../')
os.getcwd()

'c:\\Users\\nrivera\\OneDrive - PROCOLOMBIA\\Documentos\\029-App-Segmentacion-Analitica\\app-segmentacion-exportaciones'

In [3]:
# Modulo de Snowflake Analítica
import src.snowflake_analitica as snowflake_analitica

2026-08-24 15:10:47.074 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-24 15:10:47.074 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-08-24 15:10:47.075 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-24 15:10:47.075 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-24 15:10:47.076 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-24 15:10:47.076 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-24 15:10:47.076 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

### Snowflake

In [4]:
# Creación de sesión
json_path = './.streamlit/snowflake_credentials.json'
sesion_activa, conexion_activa = snowflake_analitica.create_session_from_json(json_file_path = json_path)
sesion_activa

## 1. Unión de Tejido con Municipios

In [5]:
# Cambiar ubicación de la sesión para carga de datos
snowflake_analitica.update_session_params(sesion_activa, database='APP_SEGMENTACION_EXPORTACIONES', schema='SEGMENTACION')

Base de datos cambiada a: APP_SEGMENTACION_EXPORTACIONES
Esquema cambiado a: SEGMENTACION

In [6]:
# Query para crear la TABLA que une la base de tejido y municipios
query_tabla_tejido_municipios = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P AS
SELECT -- 1. BLOQUE DE COLUMNAS ORIGINALES DE TEJIDO_EMPRESARIAL_P
        A.NIT,
        A.DIGITO_VERIFICACION,
        A.RAZON_SOCIAL,
        A.TAMANO,
        A.MACRORREGION_EMP,
        A.COD_DEPARTAMENTO_EMP,
        A.DEPARTAMENTO_EMP,
        A.COD_MUNICIPIO_EMP,
        A.MUNICIPIO_EMP,
        A.COD_CIIU_1,
        A.DESCRIPCION_CIIU_1,
        A.CADENA_CIIU_1,
        A.VALOR_AGREGADO_CIIU_1,
        A.CIIU_2,
        A.DESCRIPCION_CIIU_2,
        A.CADENA_CIIU_2,
        A.CIIU_3,
        A.DESCRIPCION_CIIU_3,
        A.CADENA_CIIU_3,
        A.CIIU_4,
        A.DESCRIPCION_CIIU_4,
        A.CADENA_CIIU_4,
        A.ANOS_EMPRESA,
        A.INVERSION_EXTRANJERA,
        A.ACTIVOS,
        A.INGRESOS_OPERACIONALES,
        A.UTILIDAD,
        A.EMPLEADOS,
        A.CANTIDAD_MUJERES_EMPLEADAS,
        A.CANTIDAD_MUJERES_EN_CARGOS_DIRECTIVOS,
        A.CANTIDAD_ESTABLECIMIENTOS,
        A.DIRECCION,
        A.TELEFONO,
        A.EMAIL,
        A.ID_REPRESENTANTE_LEGAL,
        A.REPRESENTANTE_LEGAL,
        A.ORGANIZACION_JURIDICA,
        A.CATEGORIA_MATRICULA,
        A.TIPO,
        A.CADENA,
        A.SECTOR,
        A.SUBSECTOR,
        A.COD_POSICION_ARANCELARIA,
        A.DESC_POSICION_ARANCELARIA,
        A.VALOR_AGREGADO_EXPO,
        A.COD_DEPARTAMENTO_EXPO,
        A.DEPARTAMENTO_EXPO,
        A.PAIS_DESTINO,
        A.HUB,
        A.TRAYECTORIA_EXPORTADORA,
        A.EXPO_2021,
        A.EXPO_2022,
        A.EXPO_2023,
        A.EXPO_2024,
        A.EXPO_2025,
        -- CORRIDO
        A.EXPO_ENE_MAY_2025,
        A.EXPO_ENE_MAY_2026,
        -- CORRIDO
        A.ATENDIDA_PC,
        A.NEGOCIOS,
        A.SERVICIOS,
        A.OPORTUNIDADES,
        A.NUMERO_NEGOCIOS_2023,
        A.NUMERO_NEGOCIOS_2024,
        A.NUMERO_NEGOCIOS_2025,
        -- CORRIDO
        A.NUMERO_NEGOCIOS_ENE_JUN_2026,
        -- CORRIDO
        A.NUMERO_SERVICIOS_2023,
        A.NUMERO_SERVICIOS_2024,
        A.NUMERO_SERVICIOS_2025,
        -- CORRIDO
        A.NUMERO_SERVICIOS_ENE_JUN_2026,
        -- CORRIDO
        A.NUMERO_OPORTUNIDADES_2023,
        A.NUMERO_OPORTUNIDADES_2024,
        A.NUMERO_OPORTUNIDADES_2025,
        -- CORRIDO
        A.NUMERO_OPORTUNIDADES_ENE_JUN_2026,
        -- CORRIDO
        -- COLUMNA EXPORTADORA NME
        A.EXPORTADORA AS EXPORTADORA_NME_ACTIVIDAD,
        -- COLUMNA EXPORTADORA NME
        A.CADENA_SEGMENTACION,
        A.FUENTES,
        A.POTENCIAL_ATENCION,
        A.INDICE_POTENCIAL_ATENCION,
        A.GEMELA_1, 
        A.DISTANCIA_GEMELA_1, 
        A.GEMELA_2, 
        A.DISTANCIA_GEMELA_2,
        A.GEMELA_3, 
        A.DISTANCIA_GEMELA_3,

        -- 2. BLOQUE DE COLUMNAS ORIGINALES DE BASE_MUNICIPIOS_P
        B.MENOR_200K_HABITANTES,
        B.MUNICIPIO AS MUNICIPIO_BASE_MUNICIPIOS,
        B.PDET,
        B.SUBREGION_PDET,
        B._ACT_PRIMARIAS_MUNICIPIO,
        B._ACT_SECUNDARIAS_MUNICIPIO,
        B._ACT_TERCIARIAS_MUNICIPIO,
        B._GRUPOS_ETNICOS_MUNICIPIO,
        B._INFORMALIDAD_MUNICIPIO,
        B._JOVENES_MUNICIPIO,
        B._MUJERES_MUNICIPIO,
        B._POBL_CON_DISCAPACIDAD_MUNICIPIO,
        B._POBL_CON_EDU_TECNICATECNOLOGIA_MUNICIPIO,
        B._POBL_CON_EDUCACION_MEDIA_MUNICIPIO,
        B._POBL_CON_POSGRADO_MUNICIPIO,
        B._POBL_CON_PREGRADO_MUNICIPIO,
        B._POBREZA_MUNICIPIO,
        B.POBLACION_MUNICIPIO,
        B.VALOR_AGREGADO_MUNICIPIO,
        B.ZOMAC,
        B.CODIGO_MUNICIPIO AS CODIGO_MUNICIPIO_BASE_MUNICIPIOS,
        B.CODIGO_DEPARTAMENTO AS CODIGO_DEPARTAMENTO_BASE_MUNICIPIOS,
        B.DEPARTAMENTO AS DEPARTAMENTO_BASE_MUNICIPIOS,
        -- 3. COLUMNAS CALCULADAS

        CASE 
            WHEN A.ANOS_EMPRESA >= 0 AND A.ANOS_EMPRESA <= 5 THEN 'A. 0 - 5 años'
            WHEN A.ANOS_EMPRESA > 5 AND A.ANOS_EMPRESA <= 10 THEN 'B. 6 - 10 años'
            WHEN A.ANOS_EMPRESA > 10 AND A.ANOS_EMPRESA <= 15 THEN 'C. 11 - 15 años'
            WHEN A.ANOS_EMPRESA > 15 AND A.ANOS_EMPRESA <= 20 THEN 'D. 16 - 20 años'
            WHEN A.ANOS_EMPRESA > 20 AND A.ANOS_EMPRESA <= 25 THEN 'E. 21 - 25 años'
            WHEN A.ANOS_EMPRESA > 25 AND A.ANOS_EMPRESA <= 30 THEN 'F. 26 - 30 años'
            WHEN A.ANOS_EMPRESA > 30 AND A.ANOS_EMPRESA <= 35 THEN 'G. 31 - 35 años'
            WHEN A.ANOS_EMPRESA > 35 AND A.ANOS_EMPRESA <= 40 THEN 'H. 36 - 40 años'
            WHEN A.ANOS_EMPRESA > 40 AND A.ANOS_EMPRESA <= 45 THEN 'I. 41 - 45 años'
            WHEN A.ANOS_EMPRESA > 45 AND A.ANOS_EMPRESA <= 50 THEN 'J. 46 - 50 años'
            WHEN A.ANOS_EMPRESA > 50 THEN 'K. Más de 50 años'
            ELSE 'L. Sin clasificar'
        END AS RANGO_ANTIGUEDAD,

        -- COLUMNA DE RANGO DE INGRESOS PREVIAMENTE CALCULADA CON QUANTILES
        A.RANGO_INGRESOS_TXT AS RANGO_INGRESOS,
        -- COLUMNA DE RANGO DE INGRESOS PREVIAMENTE CALCULADA CON QUANTILES

        -- INDICADORA DE EXPORTACIONES MAYORES A CERO EN CUALQUIER AÑO 
        A.HA_EXPORTADO
        -- INDICADORA DE EXPORTACIONES MAYORES A CERO EN CUALQUIER AÑO

FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.TEJIDO_EMPRESARIAL_P AS A
LEFT JOIN APP_SEGMENTACION_EXPORTACIONES.PUBLIC.BASE_MUNICIPIOS_P AS B ON A.COD_MUNICIPIO_EMP = B.CODIGO_MUNICIPIO;
"""
# Ejecutar
sesion_activa.sql(query_tabla_tejido_municipios).collect()

[Row(status='Table TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P successfully created.')]

In [7]:
# Verificación de que el left join no aumenta el número de registros en la base de tejido

# Tejido original 
query_count_tejido = "SELECT COUNT(*) FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.TEJIDO_EMPRESARIAL_P;"

# Ejecutar
count_tejido = sesion_activa.sql(query_count_tejido).collect()

# Tejido con municipios
query_count_tejido_tabla = "SELECT COUNT(*) FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P;"

# Ejecutar
count_tejido_tabla = sesion_activa.sql(query_count_tejido_tabla).collect()

In [8]:
# Verificar cantidad de registros
if count_tejido == count_tejido_tabla:
    # Mensaje de exito
    print("Ambos df tienen el mismo número de filas")
else:
    # Mensaje de error
    print("Error, el número de filas no es igual")

Ambos df tienen el mismo número de filas

In [9]:
# Identificar municipios de tejido que no cruzan
query_municipios_tabla = """
SELECT DISTINCT
    A.COD_MUNICIPIO_EMP,
    A.MUNICIPIO_EMP,
    A.MUNICIPIO_BASE_MUNICIPIOS
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P AS A
WHERE A.MUNICIPIO_BASE_MUNICIPIOS IS NULL
ORDER BY A.MUNICIPIO_EMP ASC;
"""

# Ejecutar
df_municipios_no_cruce = pd.DataFrame(sesion_activa.sql(query_municipios_tabla).collect())
df_municipios_no_cruce

  COD_MUNICIPIO_EMP   MUNICIPIO_EMP MUNICIPIO_BASE_MUNICIPIOS
0  99999             No determinado  None
1  11850             No determinado  None
2  11102             No determinado  None
3  25755             No determinado  None
4  00001             No determinado  None

In [10]:
# Exportar municipios que no cruzan para revisión data/Faltantes
df_municipios_no_cruce.to_csv("data/Faltantes/municipios_no_cruce.csv", index=False)

## 2. Creación de tablas para filtros

In [11]:
# Cambiar ubicación de la sesión para carga de datos
snowflake_analitica.update_session_params(sesion_activa, database='APP_SEGMENTACION_EXPORTACIONES', schema='SEGMENTACION')

Base de datos cambiada a: APP_SEGMENTACION_EXPORTACIONES
Esquema cambiado a: SEGMENTACION

In [12]:
# Query para filtros generales de para empresas
query_filtros_generales = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_GENERALES AS
SELECT DISTINCT 
    -- 1. BLOQUE DE COLUMNAS ORIGINALES DE BASE_MUNICIPIOS_P
    COALESCE(A.MENOR_200K_HABITANTES, 'No') AS MENOR_200K_HABITANTES,
    COALESCE(A.PDET, 'No') AS PDET,
    COALESCE(A.DEPARTAMENTO_EMP, 'No determinado') AS DEPARTAMENTO,
    COALESCE(A.MUNICIPIO_EMP, 'No determinado') AS MUNICIPIO,

    -- 2. BLOQUE DE COLUMNAS ORIGINALES DE TEJIDO_EMPRESARIAL_P
    COALESCE(A.TAMANO, 'No determinado') AS TAMANO,
    COALESCE(A.CADENA_SEGMENTACION, 'No determinado') AS CADENA_SEGMENTACION,
    COALESCE(A.TRAYECTORIA_EXPORTADORA, 'No determinado') AS TRAYECTORIA_EXPORTADORA,
    COALESCE(A.COD_CIIU_1, 'No determinado') AS COD_CIIU_1,
    COALESCE(A.DESCRIPCION_CIIU_1, 'No determinado') AS DESCRIPCION_CIIU_1,
    COALESCE(A.POTENCIAL_ATENCION, 'No determinado') AS POTENCIAL_ATENCION,
    COALESCE(A.VALOR_AGREGADO_CIIU_1, 'No determinado') AS VALOR_AGREGADO_CIIU_1,
    COALESCE(A.ATENDIDA_PC, 'No determinado') AS ATENDIDA_PC,
    COALESCE(A.SERVICIOS, 'No determinado') AS SERVICIOS,
    COALESCE(A.NEGOCIOS, 'No determinado') AS NEGOCIOS,

    -- 3. COLUMNAS CALCULADAS
    COALESCE(A.RANGO_ANTIGUEDAD, 'No determinado') AS RANGO_ANTIGUEDAD,
    COALESCE(A.RANGO_INGRESOS, 'No determinado') AS RANGO_INGRESOS,
    COALESCE(A.HA_EXPORTADO, 'No determinado') AS HA_EXPORTADO
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.TEJIDO_EMPRESARIAL_P_BASE_MUNICIPIOS_P AS A;
"""

# Ejecutar
sesion_activa.sql(query_filtros_generales).collect()

[Row(status='Table FILTROS_GENERALES successfully created.')]

In [13]:
# Query para filtros de empresas exportadoras
query_filtros_exportadoras = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_EXPORTADORAS AS
SELECT DISTINCT
    COALESCE(SECTOR, 'No determinado') AS SECTOR,
    COALESCE(SUBSECTOR, 'No determinado') AS SUBSECTOR,
    COALESCE(COD_POSICION_ARANCELARIA, 'No determinado') AS COD_POSICION_ARANCELARIA,
    COALESCE(DESC_POSICION_ARANCELARIA, 'No determinado') AS DESC_POSICION_ARANCELARIA,
    COALESCE(HUB, 'No determinado') AS HUB,
    COALESCE(PAIS_DESTINO, 'No determinado') AS PAIS_DESTINO
        
FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.BIENES_Y_SERVICIOS_P AS A;
"""

# Ejecutar
sesion_activa.sql(query_filtros_exportadoras).collect()

[Row(status='Table FILTROS_EXPORTADORAS successfully created.')]

## 3. Unión de Bienes con Tejido

In [14]:
# Cambiar ubicación de la sesión para carga de datos
snowflake_analitica.update_session_params(sesion_activa, database='APP_SEGMENTACION_EXPORTACIONES', schema='SEGMENTACION')

Base de datos cambiada a: APP_SEGMENTACION_EXPORTACIONES
Esquema cambiado a: SEGMENTACION

In [15]:
# Query para crear la tabla que une la base de bienes y tejido
query_tabla_bienes_tejido = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P AS

SELECT -- 1. BLOQUE DE COLUMNAS ORIGINALES DE BIENES_Y_SERVICIOS_P
        A.NIT AS NIT_BIENES,
        A.RAZON_SOCIAL AS RAZON_SOCIAL_BIENES,
        A.TIPO AS TIPO_BIENES,
        A.CADENA AS CADENA_BIENES,
        A.SECTOR AS SECTOR_BIENES,
        A.SUBSECTOR AS SUBSECTOR_BIENES,
        A.COD_POSICION_ARANCELARIA AS COD_POSICION_ARANCELARIA_BIENES,
        A.DESC_POSICION_ARANCELARIA AS DESC_POSICION_ARANCELARIA_BIENES,
        A.VALOR_AGREGADO_EXPO AS VALOR_AGREGADO_EXPO_BIENES,
        A.COD_DEPARTAMENTO AS COD_DEPARTAMENTO_BIENES,
        A.DEPARTAMENTO AS DEPARTAMENTO_BIENES,
        A.MACRORREGION AS MACRORREGION_BIENES,
        A.PAIS_DESTINO AS PAIS_DESTINO_BIENES,
        A.CONTINENTE AS CONTINENTE_BIENES,
        A.HUB AS HUB_BIENES,
        A.ZONA_GEOGRAFICA AS ZONA_GEOGRAFICA_BIENES,
        A.FUENTE AS FUENTE_BIENES,
        A.VALOR_FOB_USD_2021 AS VALOR_FOB_USD_2021_BIENES,
        A.VALOR_FOB_USD_2022 AS VALOR_FOB_USD_2022_BIENES,
        A.VALOR_FOB_USD_2023 AS VALOR_FOB_USD_2023_BIENES,
        A.VALOR_FOB_USD_2024 AS VALOR_FOB_USD_2024_BIENES,
        A.VALOR_FOB_USD_2025 AS VALOR_FOB_USD_2025_BIENES,
        -- CORRIDO
        A.VALOR_FOB_USD_ENE_MAY_2025 AS VALOR_FOB_USD_ENE_MAY_2025_BIENES,
        A.VALOR_FOB_USD_ENE_MAY_2026 AS VALOR_FOB_USD_ENE_MAY_2026_BIENES,
        -- CORRIDO
        A.CADENA_SEGMENTACION AS CADENA_SEGMENTACION_BIENES,

        -- Crear columna de concatenación de código de posición arancelaria y descripción
        CONCAT(A.COD_POSICION_ARANCELARIA, ' - ', A.DESC_POSICION_ARANCELARIA) AS POSICION_ARANCELARIA_COMPLETA_BIENES,

        -- 2. BLOQUE DE COLUMNAS ORIGINALES DE TEJIDO_EMPRESARIAL_P
        B.NIT AS NIT_TEJIDO,
        B.DIGITO_VERIFICACION AS DIGITO_VERIFICACION_TEJIDO,
        B.RAZON_SOCIAL AS RAZON_SOCIAL_TEJIDO,
        B.TAMANO AS TAMANO_TEJIDO,
        B.MACRORREGION_EMP AS MACRORREGION_TEJIDO,
        B.COD_DEPARTAMENTO_EMP AS COD_DEPARTAMENTO_TEJIDO,
        B.DEPARTAMENTO_EMP AS DEPARTAMENTO_TEJIDO,
        B.COD_MUNICIPIO_EMP AS COD_MUNICIPIO_TEJIDO,
        B.MUNICIPIO_EMP AS MUNICIPIO_TEJIDO,
        B.COD_CIIU_1 AS COD_CIIU_1_TEJIDO,
        B.DESCRIPCION_CIIU_1 AS DESCRIPCION_CIIU_1_TEJIDO,
        B.CADENA_CIIU_1 AS CADENA_CIIU_1_TEJIDO,
        B.VALOR_AGREGADO_CIIU_1 AS VALOR_AGREGADO_CIIU_1_TEJIDO,
        B.CIIU_2 AS CIIU_2_TEJIDO,
        B.DESCRIPCION_CIIU_2 AS DESCRIPCION_CIIU_2_TEJIDO,
        B.CADENA_CIIU_2 AS CADENA_CIIU_2_TEJIDO,
        B.CIIU_3 AS CIIU_3_TEJIDO,
        B.DESCRIPCION_CIIU_3 AS DESCRIPCION_CIIU_3_TEJIDO,
        B.CADENA_CIIU_3 AS CADENA_CIIU_3_TEJIDO,
        B.CIIU_4 AS CIIU_4_TEJIDO,
        B.DESCRIPCION_CIIU_4 AS DESCRIPCION_CIIU_4_TEJIDO,
        B.CADENA_CIIU_4 AS CADENA_CIIU_4_TEJIDO,
        B.ANOS_EMPRESA AS ANOS_EMPRESA_TEJIDO,
        B.INVERSION_EXTRANJERA AS INVERSION_EXTRANJERA_TEJIDO,
        B.ACTIVOS AS ACTIVOS_TEJIDO,
        B.INGRESOS_OPERACIONALES AS INGRESOS_OPERACIONALES_TEJIDO,
        -- COLUMNA DE RANGO DE INGRESOS PREVIAMENTE CALCULADA CON QUANTILES
        B.RANGO_INGRESOS_TXT AS RANGO_INGRESOS,
        -- COLUMNA DE RANGO DE INGRESOS PREVIAMENTE CALCULADA CON QUANTILES
        B.UTILIDAD AS UTILIDAD_TEJIDO,
        B.EMPLEADOS AS EMPLEADOS_TEJIDO,
        B.CANTIDAD_MUJERES_EMPLEADAS AS CANTIDAD_MUJERES_EMPLEADAS_TEJIDO,
        B.CANTIDAD_MUJERES_EN_CARGOS_DIRECTIVOS AS CANTIDAD_MUJERES_EN_CARGOS_DIRECTIVOS_TEJIDO,
        B.CANTIDAD_ESTABLECIMIENTOS AS CANTIDAD_ESTABLECIMIENTOS_TEJIDO,
        B.DIRECCION AS DIRECCION_TEJIDO,
        B.TELEFONO AS TELEFONO_TEJIDO,
        B.EMAIL AS EMAIL_TEJIDO,
        B.ID_REPRESENTANTE_LEGAL AS ID_REPRESENTANTE_LEGAL_TEJIDO,
        B.REPRESENTANTE_LEGAL AS REPRESENTANTE_LEGAL_TEJIDO,
        B.ORGANIZACION_JURIDICA AS ORGANIZACION_JURIDICA_TEJIDO,
        B.CATEGORIA_MATRICULA AS CATEGORIA_MATRICULA_TEJIDO,
        B.TIPO AS TIPO_TEJIDO,
        B.CADENA AS CADENA_TEJIDO,
        B.SECTOR AS SECTOR_TEJIDO,
        B.SUBSECTOR AS SUBSECTOR_TEJIDO,
        B.COD_POSICION_ARANCELARIA AS COD_POSICION_ARANCELARIA_TEJIDO,
        B.DESC_POSICION_ARANCELARIA AS DESC_POSICION_ARANCELARIA_TEJIDO,
        B.VALOR_AGREGADO_EXPO AS VALOR_AGREGADO_EXPO_TEJIDO,
        B.COD_DEPARTAMENTO_EXPO AS COD_DEPARTAMENTO_EXPO_TEJIDO,
        B.DEPARTAMENTO_EXPO AS DEPARTAMENTO_EXPO_TEJIDO,
        B.PAIS_DESTINO AS PAIS_DESTINO_TEJIDO,
        B.HUB AS HUB_TEJIDO,
        B.TRAYECTORIA_EXPORTADORA AS TRAYECTORIA_EXPORTADORA_TEJIDO,
        B.EXPO_2021 AS EXPO_2021_TEJIDO,
        B.EXPO_2022 AS EXPO_2022_TEJIDO,
        B.EXPO_2023 AS EXPO_2023_TEJIDO,
        B.EXPO_2024 AS EXPO_2024_TEJIDO,
        B.EXPO_2025 AS EXPO_2025_TEJIDO,
        -- CORRIDO
        B.EXPO_ENE_MAY_2025 AS EXPO_ENE_MAY_2025_TEJIDO,
        B.EXPO_ENE_MAY_2026 AS EXPO_ENE_MAY_2026_TEJIDO,
        -- CORRIDO
        -- INDICADORA DE EXPORTACIONES MAYORES A CERO EN CUALQUIER AÑO 
        B.HA_EXPORTADO AS HA_EXPORTADO_TEJIDO,
        -- INDICADORA DE EXPORTACIONES MAYORES A CERO EN CUALQUIER AÑO
        B.ATENDIDA_PC AS ATENDIDA_PC_TEJIDO,
        B.NEGOCIOS AS NEGOCIOS_TEJIDO,
        B.SERVICIOS AS SERVICIOS_TEJIDO,
        B.OPORTUNIDADES AS OPORTUNIDADES_TEJIDO,
        B.NUMERO_NEGOCIOS_2023 AS NUMERO_NEGOCIOS_2023_TEJIDO,
        B.NUMERO_NEGOCIOS_2024 AS NUMERO_NEGOCIOS_2024_TEJIDO,
        B.NUMERO_NEGOCIOS_2025 AS NUMERO_NEGOCIOS_2025_TEJIDO,
        -- CORRIDO
        B.NUMERO_NEGOCIOS_ENE_JUN_2026 AS NUMERO_NEGOCIOS_ENE_JUN_2026_TEJIDO,
        -- CORRIDO
        B.NUMERO_SERVICIOS_2023 AS NUMERO_SERVICIOS_2023_TEJIDO,
        B.NUMERO_SERVICIOS_2024 AS NUMERO_SERVICIOS_2024_TEJIDO,
        B.NUMERO_SERVICIOS_2025 AS NUMERO_SERVICIOS_2025_TEJIDO,
        -- CORRIDO
        B.NUMERO_SERVICIOS_ENE_JUN_2026 AS NUMERO_SERVICIOS_ENE_JUN_2026_TEJIDO,
        -- CORRIDO
        B.NUMERO_OPORTUNIDADES_2023 AS NUMERO_OPORTUNIDADES_2023_TEJIDO,
        B.NUMERO_OPORTUNIDADES_2024 AS NUMERO_OPORTUNIDADES_2024_TEJIDO,
        B.NUMERO_OPORTUNIDADES_2025 AS NUMERO_OPORTUNIDADES_2025_TEJIDO,
        -- CORRIDO
        B.NUMERO_OPORTUNIDADES_ENE_JUN_2026 AS NUMERO_OPORTUNIDADES_ENE_JUN_2026_TEJIDO,
        -- CORRIDO
        -- COLUMNA EXPORTADORA NME
        B.EXPORTADORA AS EXPORTADORA_NME_ACTIVIDAD,
        -- COLUMNA EXPORTADORA NME
        B.CADENA_SEGMENTACION AS CADENA_SEGMENTACION_TEJIDO,
        B.FUENTES AS FUENTES_TEJIDO,
        B.POTENCIAL_ATENCION AS POTENCIAL_ATENCION_TEJIDO,
        B.INDICE_POTENCIAL_ATENCION AS INDICE_POTENCIAL_ATENCION_TEJIDO,
        B.GEMELA_1 AS GEMELA_1_TEJIDO, 
        B.DISTANCIA_GEMELA_1 AS DISTANCIA_GEMELA_1_TEJIDO, 
        B.GEMELA_2 AS GEMELA_2_TEJIDO, 
        B.DISTANCIA_GEMELA_2 AS DISTANCIA_GEMELA_2_TEJIDO,
        B.GEMELA_3 AS GEMELA_3_TEJIDO, 
        B.DISTANCIA_GEMELA_3 AS DISTANCIA_GEMELA_3_TEJIDO,
        
        -- 3. BLOQUE DE COLUMNAS ORIGINALES DE CORRELATIVA_DEPARTAMENTOS
        C.DEPTO_ORIGEN AS DEPTO_ORIGEN_CORRELATIVA

FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.BIENES_Y_SERVICIOS_P AS A
    LEFT JOIN APP_SEGMENTACION_EXPORTACIONES.PUBLIC.TEJIDO_EMPRESARIAL_P AS B ON A.NIT = B.NIT AND A.RAZON_SOCIAL = B.RAZON_SOCIAL
    LEFT JOIN APP_SEGMENTACION_EXPORTACIONES.PUBLIC.CORRELATIVA_DEPARTAMENTOS AS C ON C.CODIGO_DEPTO_ORIGEN = A.COD_DEPARTAMENTO;
    
"""

# Ejecutar
sesion_activa.sql(query_tabla_bienes_tejido).collect()

[Row(status='Table BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P successfully created.')]

In [16]:
# Verificación de que el left join no aumenta el número de registros en la base de bienes y servicios

# Bienes original 
query_count_bienes = "SELECT COUNT(*) FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.BIENES_Y_SERVICIOS_P;"

# Ejecutar
count_bienes = sesion_activa.sql(query_count_bienes).collect()

# Bienes con Tejido
query_count_bienes_tabla = "SELECT COUNT(*) FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P;"

# Ejecutar
count_bienes_tabla = sesion_activa.sql(query_count_bienes_tabla).collect()

In [17]:
# Verificar cantidad de registros
if count_bienes == count_bienes_tabla:
    # Mensaje de exito
    print("Ambos df tienen el mismo número de filas")
else:
    # Mensaje de error
    print("Error, el número de filas no es igual")

Ambos df tienen el mismo número de filas

In [18]:
# Identificar empresas de bienes que no cruzan
query_bienes_tabla = """
SELECT DISTINCT 
    A.NIT_BIENES,
	A.RAZON_SOCIAL_BIENES
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P AS A
WHERE A.TAMANO_TEJIDO IS NULL;
"""

# Ejecutar
df_empresas_no_cruce = pd.DataFrame(sesion_activa.sql(query_bienes_tabla).collect())
df_empresas_no_cruce

     NIT_BIENES                                RAZON_SOCIAL_BIENES
0     900292385  GLOBAL  LOGISTIC TRADE SAS
1     901132131  ORIX PACK S.A.S.
2     901617190  THINKPLAST S.A.S.
3     901070418  TRELLEBORG PIPE SEALS COLOMBIA SAS EN LIQUIDACION
4     900229816  TECNO-FIX SAS
...         ...            ...
6502  900273390  CHEMCO S.A.S.
6503  830122711  PACIFIC PETROLEUM ENERGY S A
6504  900067444  GENSER POWER COLOMBIA
6505  901179044  MIXING & EQUIPOS S.A.S
6506  900034591  MAR ANTIGUO S.A.S.

[6507 rows x 2 columns]

In [19]:
# Exportar empresas que no cruzan para revisión data/Faltantes
df_empresas_no_cruce.to_csv("data/Faltantes/empresas_no_cruce.csv", index=False)

In [20]:
# Identificar los departamentos que no cruzan
query_departamentos_tabla = """
SELECT DISTINCT A.COD_DEPARTAMENTO_BIENES,
    A.DEPARTAMENTO_BIENES
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P AS A
WHERE A.DEPTO_ORIGEN_CORRELATIVA IS NULL
"""

# Ejecutar
df_departamentos_no_cruce = pd.DataFrame(sesion_activa.sql(query_departamentos_tabla).collect())
df_departamentos_no_cruce

Empty DataFrame
Columns: []
Index: []

### 3.1 Creación de tabla para filtros de destino y valor agregado

In [21]:
# Cambiar ubicación de la sesión para carga de datos
snowflake_analitica.update_session_params(sesion_activa, database='APP_SEGMENTACION_EXPORTACIONES', schema='SEGMENTACION')

Base de datos cambiada a: APP_SEGMENTACION_EXPORTACIONES
Esquema cambiado a: SEGMENTACION

In [22]:
# Query para filtros de bienes
query_filtros_bienes = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_BIENES AS
SELECT DISTINCT
    COALESCE(A.CADENA_BIENES,'No determinado') AS CADENA_BIENES,
    COALESCE(A.SECTOR_BIENES,'No determinado') AS SECTOR_BIENES,
    COALESCE(A.SUBSECTOR_BIENES,'No determinado') AS SUBSECTOR_BIENES,
    COALESCE(A.COD_POSICION_ARANCELARIA_BIENES,'No determinado') AS COD_POSICION_ARANCELARIA_BIENES,
    COALESCE(A.DESC_POSICION_ARANCELARIA_BIENES,'No determinado') AS DESC_POSICION_ARANCELARIA_BIENES,
    COALESCE(A.PAIS_DESTINO_BIENES,'No determinado') AS PAIS_DESTINO_BIENES,
    COALESCE(A.HUB_BIENES,'No determinado') AS HUB_BIENES,
    COALESCE(A.VALOR_AGREGADO_EXPO_BIENES,'No determinado') AS VALOR_AGREGADO_EXPO_BIENES,
    COALESCE(A.TAMANO_TEJIDO, 'No determinado') AS TAMANO_TEJIDO,
    COALESCE(A.INVERSION_EXTRANJERA_TEJIDO, 'No determinado') AS SUCURSAL_SOCIEDAD_EXTRANJERA
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.BIENES_Y_SERVICIOS_P_TEJIDO_EMPRESARIAL_P AS A;
"""

# Ejecutar
sesion_activa.sql(query_filtros_bienes).collect()

[Row(status='Table FILTROS_BIENES successfully created.')]

## 4. Tablas para departamentos y municipios

In [23]:
# Cambiar ubicación de la sesión para carga de datos
snowflake_analitica.update_session_params(sesion_activa, database='APP_SEGMENTACION_EXPORTACIONES', schema='SEGMENTACION')

Base de datos cambiada a: APP_SEGMENTACION_EXPORTACIONES
Esquema cambiado a: SEGMENTACION

In [24]:
# Query para tabla de servicios ProColombia por departamento
query_servicios_departamentos = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.DEPARTAMENTOS_SERVICIOS AS
SELECT A.COD_DEPARTAMENTO_EMP AS CODIGO_DEPARTAMENTO_TEJIDO,
    A.DEPARTAMENTO_EMP AS DEPARTAMENTO_TEJIDO,
    A.CADENA_SEGMENTACION AS CADENA_SEGMENTACION_TEJIDO,
    A.NIT AS NIT_TEJIDO,
    -- CORRIDO
    COALESCE(A.NUMERO_SERVICIOS_2023, 0) + COALESCE(A.NUMERO_SERVICIOS_2024, 0) + COALESCE(A.NUMERO_SERVICIOS_2025, 0) + COALESCE(A.NUMERO_SERVICIOS_ENE_JUN_2026, 0) AS TOTAL_SERVICIOS_OFRECIDOS_TEJIDO,
    -- CORRIDO
    A.SERVICIOS AS EMPRESA_CON_SERVICIOS_TEJIDO
FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.TEJIDO_EMPRESARIAL_P AS A;
"""

# Ejecutar
sesion_activa.sql(query_servicios_departamentos).collect()

[Row(status='Table DEPARTAMENTOS_SERVICIOS successfully created.')]

In [25]:
# Query para tabla de exportaciones por departamento
query_exportaciones_departamentos = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.DEPARTAMENTOS_EXPORTACIONES AS
SELECT  A.CADENA AS CADENA_PRODUCTIVA_BIENES_SERVICIOS,
        A.SECTOR AS SECTOR_BIENES_SERVICIOS,
        A.SUBSECTOR AS SUBSECTOR_BIENES_SERVICIOS,
        A.COD_POSICION_ARANCELARIA AS COD_POSICION_ARANCELARIA_BIENES_SERVICIOS,
        A.DESC_POSICION_ARANCELARIA AS DESC_POSICION_ARANCELARIA_BIENES_SERVICIOS,
        A.COD_DEPARTAMENTO AS CODIGO_DEPARTAMENTO_BIENES_SERVICIOS,
        A.DEPARTAMENTO AS DEPARTAMENTO_BIENES_SERVICIOS,
        A.NIT AS NIT_BIENES_SERVICIOS,
        B.TAMANO AS TAMANO_EMPRESA_TEJIDO,
        A.VALOR_FOB_USD_2021 AS VALOR_FOB_USD_2021_BIENES,
        A.VALOR_FOB_USD_2022 AS VALOR_FOB_USD_2022_BIENES,
        A.VALOR_FOB_USD_2023 AS VALOR_FOB_USD_2023_BIENES,
        A.VALOR_FOB_USD_2024 AS VALOR_FOB_USD_2024_BIENES,
        A.VALOR_FOB_USD_2025 AS VALOR_FOB_USD_2025_BIENES,
        -- CORRIDO
        A.VALOR_FOB_USD_ENE_MAY_2025 AS VALOR_FOB_USD_ENE_MAY_2025_BIENES,
        A.VALOR_FOB_USD_ENE_MAY_2026 AS VALOR_FOB_USD_ENE_MAY_2026_BIENES
        -- CORRIDO

FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.BIENES_Y_SERVICIOS_P AS A
    LEFT JOIN APP_SEGMENTACION_EXPORTACIONES.PUBLIC.TEJIDO_EMPRESARIAL_P AS B ON A.NIT = B.NIT;
"""

# Ejecutar
sesion_activa.sql(query_exportaciones_departamentos).collect()

[Row(status='Table DEPARTAMENTOS_EXPORTACIONES successfully created.')]

In [26]:
# Query para tabla de exportaciones por municipio
query_exportaciones_municipios = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.MUNICIPIOS_EXPORTACIONES AS
SELECT  A.COD_DEPARTAMENTO_EMP AS CODIGO_DEPARTAMENTO_TEJIDO,
        A.DEPARTAMENTO_EMP AS DEPARTAMENTO_TEJIDO,
        A.COD_MUNICIPIO_EMP AS CODIGO_MUNICIPIO_TEJIDO,
        A.MUNICIPIO_EMP AS MUNICIPIO_TEJIDO,
        A.CADENA_SEGMENTACION AS CADENA_SEGMENTACION_TEJIDO,
        A.CADENA AS CADENA_PRODUCTIVA_TEJIDO,
        A.SECTOR AS SECTOR_TEJIDO,
        A.SUBSECTOR AS SUBSECTOR_TEJIDO,
        A.NIT AS NIT_TEJIDO,
        -- CORRIDO
        A.NUMERO_SERVICIOS_2023 + A.NUMERO_SERVICIOS_2024 + A.NUMERO_SERVICIOS_2025 + A.NUMERO_SERVICIOS_ENE_JUN_2026 AS TOTAL_SERVICIOS_OFRECIDOS_TEJIDO,
        -- CORRIDO
        A.SERVICIOS AS EMPRESA_CON_SERVICIOS_TEJIDO,
        A.EXPO_2021,
        A.EXPO_2022,
        A.EXPO_2023,
        A.EXPO_2024,
        A.EXPO_2025,
        -- CORRIDO
        A.EXPO_ENE_MAY_2025,
        A.EXPO_ENE_MAY_2026,
        -- CORRIDO
        B.MENOR_200K_HABITANTES,
        B.MUNICIPIO AS MUNICIPIO_BASE_MUNICIPIOS,
        B.PDET,
        B.SUBREGION_PDET,
        B._ACT_PRIMARIAS_MUNICIPIO,
        B._ACT_SECUNDARIAS_MUNICIPIO,
        B._ACT_TERCIARIAS_MUNICIPIO,
        B._GRUPOS_ETNICOS_MUNICIPIO,
        B._INFORMALIDAD_MUNICIPIO,
        B._JOVENES_MUNICIPIO,
        B._MUJERES_MUNICIPIO,
        B._POBL_CON_DISCAPACIDAD_MUNICIPIO,
        B._POBL_CON_EDU_TECNICATECNOLOGIA_MUNICIPIO,
        B._POBL_CON_EDUCACION_MEDIA_MUNICIPIO,
        B._POBL_CON_POSGRADO_MUNICIPIO,
        B._POBL_CON_PREGRADO_MUNICIPIO,
        B._POBREZA_MUNICIPIO,
        B.POBLACION_MUNICIPIO,
        B.VALOR_AGREGADO_MUNICIPIO,
        B.ZOMAC,
        B.CODIGO_MUNICIPIO AS CODIGO_MUNICIPIO_BASE_MUNICIPIOS,
        B.CODIGO_DEPARTAMENTO AS CODIGO_DEPARTAMENTO_BASE_MUNICIPIOS_P,
        B.DEPARTAMENTO AS DEPARTAMENTO_BASE_MUNICIPIOS_P

FROM APP_SEGMENTACION_EXPORTACIONES.PUBLIC.TEJIDO_EMPRESARIAL_P AS A
LEFT JOIN APP_SEGMENTACION_EXPORTACIONES.PUBLIC.BASE_MUNICIPIOS_P AS B ON A.COD_MUNICIPIO_EMP = B.CODIGO_MUNICIPIO;
"""

# Ejecutar
sesion_activa.sql(query_exportaciones_municipios).collect()

[Row(status='Table MUNICIPIOS_EXPORTACIONES successfully created.')]

## 5. Filtros de páginas de departamentos y municipios

In [27]:
# Cambiar ubicación de la sesión para carga de datos
snowflake_analitica.update_session_params(sesion_activa, database='APP_SEGMENTACION_EXPORTACIONES', schema='SEGMENTACION')

Base de datos cambiada a: APP_SEGMENTACION_EXPORTACIONES
Esquema cambiado a: SEGMENTACION

In [28]:
# Query para filtros de departamentos servicios
query_filtros_departamentos_servicios = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_DEPARTAMENTOS_SERVICIOS AS
SELECT DISTINCT 
    COALESCE(DEPARTAMENTO_TEJIDO, 'No determinado') AS DEPARTAMENTO_TEJIDO,
    COALESCE(CADENA_SEGMENTACION_TEJIDO, 'No determinado') AS CADENA_SEGMENTACION_TEJIDO
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.DEPARTAMENTOS_SERVICIOS;
"""

# Ejecutar
sesion_activa.sql(query_filtros_departamentos_servicios).collect()

[Row(status='Table FILTROS_DEPARTAMENTOS_SERVICIOS successfully created.')]

In [29]:
# Query para filtros de departamentos exportaciones
query_filtros_departamentos_exportaciones = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_DEPARTAMENTOS_EXPORTACIONES AS
SELECT DISTINCT 
    COALESCE(CADENA_PRODUCTIVA_BIENES_SERVICIOS, 'No determinado') AS CADENA_PRODUCTIVA_BIENES_SERVICIOS,
    COALESCE(SECTOR_BIENES_SERVICIOS, 'No determinado') AS SECTOR_BIENES_SERVICIOS,
    COALESCE(SUBSECTOR_BIENES_SERVICIOS, 'No determinado') AS SUBSECTOR_BIENES_SERVICIOS,
    COALESCE(COD_POSICION_ARANCELARIA_BIENES_SERVICIOS, 'No determinado') AS COD_POSICION_ARANCELARIA_BIENES_SERVICIOS,
    COALESCE(DESC_POSICION_ARANCELARIA_BIENES_SERVICIOS, 'No determinado') AS DESC_POSICION_ARANCELARIA_BIENES_SERVICIOS
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.DEPARTAMENTOS_EXPORTACIONES;
"""

# Ejecutar
sesion_activa.sql(query_filtros_departamentos_exportaciones).collect()

[Row(status='Table FILTROS_DEPARTAMENTOS_EXPORTACIONES successfully created.')]

In [30]:
# Query para filtros de municipios exportaciones
query_filtros_municipios_exportaciones = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_MUNICIPIOS_EXPORTACIONES AS
SELECT DISTINCT A.DEPARTAMENTO_TEJIDO,
	COALESCE(A.MUNICIPIO_TEJIDO, 'No determinado') AS MUNICIPIO_TEJIDO,
	COALESCE(A.PDET, 'No determinado') AS PDET,
	COALESCE(A.MENOR_200K_HABITANTES, 'No determinado') AS MENOR_200K_HABITANTES
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.MUNICIPIOS_EXPORTACIONES AS A;
"""

# Ejecutar
sesion_activa.sql(query_filtros_municipios_exportaciones).collect()

[Row(status='Table FILTROS_MUNICIPIOS_EXPORTACIONES successfully created.')]

In [31]:
# Query para filtros de municipios información socieconómica
query_filtros_municipios_socioec = """
CREATE OR REPLACE TABLE APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.FILTROS_MUNICIPIOS_SOCIOEC AS
SELECT DISTINCT A.DEPARTAMENTO_TEJIDO,
	COALESCE(A.MUNICIPIO_TEJIDO, 'No determinado') AS MUNICIPIO_TEJIDO,
	COALESCE(A.PDET, 'No determinado') AS PDET,
	COALESCE(A.MENOR_200K_HABITANTES, 'No determinado') AS MENOR_200K_HABITANTES,
    COALESCE(A.ZOMAC, 'No determinado') AS ZOMAC
FROM APP_SEGMENTACION_EXPORTACIONES.SEGMENTACION.MUNICIPIOS_EXPORTACIONES AS A;
"""

# Ejecutar
sesion_activa.sql(query_filtros_municipios_socioec).collect()

[Row(status='Table FILTROS_MUNICIPIOS_SOCIOEC successfully created.')]

## Cerrar sesión, conexión y cursor

In [32]:
sesion_activa.close()